### ISSUE TITLE
Small issue installing with python 3.10

### ISSUE THREAD

**Issue by JanStreffing** [FESOM/tripyview#118]
I just installed tripyrun from the workbench into a clean python 3.10 environment. I get the following incompatibility. 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paramiko 3.4.0 requires cryptography>=3.3, which is not installed.
pyarrow 15.0.0 requires numpy<2,>=1.16.6, but you have numpy 2.0.0 which is incompatible.
```

When I manually install:
```
pip install "numpy<2.0"
pip install "cryptography>=3.3"
pip install pyarrow
pip install paramiko
...
pip install -e .

Installing collected packages: tripyview
  Attempting uninstall: tripyview
    Found existing installation: tripyview 0.3.0
    Uninstalling tripyview-0.3.0:
      Successfully uninstalled tripyview-0.3.0
  Running setup.py develop for tripyview
Successfully installed tripyview-0.3.0
```

**Comment by patrickscholz** [comment]
@JanStreffing: I just tried the same earlier on albedo, an i didnt have any of that issue! ... Strange!

**Comment by patrickscholz** [comment]
do you use conda  or the module environment ?

**Comment by patrickscholz** [comment]
@JanStreffing: I cant reproduce that issue. However i tested now on albedo up to python version 3.12 and there havent been anymore error message, except that occasionally the dask client seems to loose its connectivity but manages to proceed with it!
