### ISSUE TITLE
SST Climatology

### ISSUE THREAD

**Issue by alxthor** [FESOM/tripyview#158]
Is there currently a way to compute SST biases/anomalies with respect to climatology?

using `do_clim = True` does nothing if `vname = "sst"`. So computing SST climatology might only work with the 3D temperature field and setting depth to 0?

See in `template_hslice.ipynb`:
```python
#___APPEND ABS CLIMATOLOGY_____________________________________________________________________________    
if (vname in ['temp', 'salt', 'pdens'] or 'sigma' in vname) and (depth != 'bottom') and do_clim and (ref_path is None): 
```

**Comment by patrickscholz** [comment]
I assume here to compute climatological differences always from the ```temp``` 3d field not from ```sst``` but that can be changed

**Comment by patrickscholz** [comment]
if you try it for vname ='temp' and depth=2.5 tripyview should do it!

**Comment by patrickscholz** [comment]
Ok fixed that in the main branch
